Ml pipeline rewrite
crux-bphc/snap-sorter pull request #40
Opened 2023-07-28 18:41 UTC by shailx383

-   **Please check if the PR fulfills these requirements**

*   [x] The commit message follows our guidelines
*   [x] Tests for the changes have been added (for bug fixes / features)
*   [] Docs have been added / updated (for bug fixes / features)
*   [x] The code runs on the contributors machine.
*   [x] The code follows the code style guide of this project.

-   **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
refactor 
-   **What is the current behavior?** (You can also link to an open issue here)
pipeline works with inception resnet
-   **What is the new behavior (if this is a feature change)?**
included FaceNet from model.py
-   **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
no
-   **Other information**:

2023-07-29 15:04 UTC, adityapentyala commented
Works when commit 64c5cdf is reverted, with the exception of removing `points.data[0].numpy()` in favour of `points.data.numpy()` on line 90. Check if it works after changes. The rest of it works perfectly so I'll push if the change works

2023-07-29 15:29 UTC, adityapentyala requested changes
also, could you add tqdm to the env file? had to install that but again it might be a problem with only my env

2023-07-30 10:47 UTC, shailx383 commented
removed tqdm as it is not required

2023-07-30 11:06 UTC, adityapentyala approved these changes

2023-07-30 11:15 UTC, adityapentyala requested changes

2023-07-30 11:15 UTC, adityapentyala commented on clusterer/datapoint_clusterer.py
line 90 still throws an error when only `point.data` is written. code runs perfectly with `point.data.numpy()`

2023-07-30 11:57 UTC, adityapentyala approved these changes
LGTM, merging

2023-07-30 11:59 UTC, merged